import { bookLanguage } from "./bookMetadata.js";

const strings = {
  es: {
    searchLibrary: "Buscar por título, autor o año", searchLibraryPlaceholder: "Título, autor o año",
    novels: "Novelas", graphicNovels: "Novelas gráficas", graphicNovel: "Novela gráfica", bookType: "Tipo de libro",
    typeHint: "Sin marcar: novela. Márcalo si es una novela gráfica o un cómic.", batchTypeHint: "Sin marcar: novela. Esta selección se aplica a todos los archivos de la subida; puedes cambiarla después en cada ficha.",
    collectionTypeHint: "Al cambiar esta casilla se aplica el tipo a todos los libros de la colección, incluidos los que no aparecen en el filtro actual. Sin marcar: novela.",
    sort: "Ordenar por", sortName: "Nombre", sortAuthor: "Autor", actions: "Acciones", showActions: "Mostrar acciones de libros", hideActions: "Ocultar acciones de libros", download: "Descargar", emptyNovels: "No hay novelas", emptyGraphicNovels: "No hay novelas gráficas",
    catalogPages: "Páginas de la edición consultada en Open Library; pueden diferir de las pantallas del lector.", missingPages: "Open Library no indica las páginas de esta edición. Puedes introducirlas manualmente.",
    epubPageList: "Páginas referenciadas en el EPUB. Pueden diferir de las pantallas del lector.", epubFixedPages: "Páginas obtenidas de la maquetación fija del EPUB.",
    library: "Biblioteca · Open Library", uploadTitle: "Identifica el libro antes de subirlo", infoTitle: "Información del libro", close: "Cerrar", file: "Archivo",
    intro: "Busca y selecciona una coincidencia, revisa la ficha y confirma que es tu libro. También puedes completar los datos manualmente.",
    searchLabel: "Buscar por título, autor o ISBN", searching: "Buscando…", search: "Buscar", loading: "Recuperando la ficha y los idiomas disponibles…",
    noResults: "No se han encontrado coincidencias. Prueba con otro título o ISBN, o completa la ficha manualmente.", unknownAuthor: "Autor desconocido",
    hint: "Se guardan los textos disponibles en castellano, catalán e inglés. La ficha sigue el idioma del sistema; ISBN y editorial corresponden a la edición seleccionada. Las páginas se consultan en Open Library; si faltan, se usa la paginación disponible en el EPUB.",
    fallback: "No hay sinopsis en este idioma. Se muestra el texto original disponible; puedes añadir una versión manualmente.",
    locale: "Idioma de los textos", savedProfile: "Ficha que se guardará", title: "Título", subtitle: "Subtítulo", author: "Autores", year: "Año", isbn: "ISBN", publisher: "Editorial", publishDate: "Fecha de publicación", language: "Idioma de la edición", pageCount: "Páginas", subjects: "Temas / géneros", description: "Sinopsis", coverUrl: "URL de portada",
    fileCover: "Usar portada del archivo", localCover: "Portada desde el equipo", deleteBook: "Borrar libro completo", cancel: "Cancelar", saving: "Guardando…", confirmUpload: "Confirmar libro y subir", confirmSave: "Confirmar y guardar ficha", refresh: "Actualizar los tres idiomas",
    searchError: "No se pudo consultar Open Library.", detailsError: "No se pudo recuperar la ficha.", saveError: "No se pudo guardar la ficha.",
    collection: "Colección", yourLibrary: "Tu biblioteca", read: "Leer", edit: "Editar ficha", lookup: "Buscar información del libro", remove: "Eliminar", format: "Formato", topics: "Temas", source: "Ficha original en Open Library ↗",
    noDescription: "Todavía no hay sinopsis. Busca el libro en Open Library o completa su ficha.", empty: "No hay libros", emptyHint: "Sube un archivo o una carpeta con una colección.", enter: "Entrar", customize: "Personalizar",
  },
  ca: {
    searchLibrary: "Cercar per títol, autor o any", searchLibraryPlaceholder: "Títol, autor o any",
    novels: "Novel·les", graphicNovels: "Novel·les gràfiques", graphicNovel: "Novel·la gràfica", bookType: "Tipus de llibre",
    typeHint: "Sense marcar: novel·la. Marca-ho si és una novel·la gràfica o un còmic.", batchTypeHint: "Sense marcar: novel·la. Aquesta selecció s'aplica a tots els fitxers de la pujada; pots canviar-la després a cada fitxa.",
    collectionTypeHint: "En canviar aquesta casella, el tipus s’aplica a tots els llibres de la col·lecció, inclosos els que no apareixen al filtre actual. Sense marcar: novel·la.",
    sort: "Ordenar per", sortName: "Nom", sortAuthor: "Autor", actions: "Accions", showActions: "Mostrar accions dels llibres", hideActions: "Amagar accions dels llibres", download: "Descarregar", emptyNovels: "No hi ha novel·les", emptyGraphicNovels: "No hi ha novel·les gràfiques",
    catalogPages: "Pàgines de l'edició consultada a Open Library; poden diferir de les pantalles del lector.", missingPages: "Open Library no indica les pàgines d'aquesta edició. Pots introduir-les manualment.",
    epubPageList: "Pàgines referenciades a l'EPUB. Poden diferir de les pantalles del lector.", epubFixedPages: "Pàgines obtingudes de la maquetació fixa de l'EPUB.",
    library: "Biblioteca · Open Library", uploadTitle: "Identifica el llibre abans de pujar-lo", infoTitle: "Informació del llibre", close: "Tancar", file: "Fitxer",
    intro: "Cerca i selecciona una coincidència, revisa la fitxa i confirma que és el teu llibre. També pots completar les dades manualment.",
    searchLabel: "Cercar per títol, autor o ISBN", searching: "Cercant…", search: "Cercar", loading: "Recuperant la fitxa i els idiomes disponibles…",
    noResults: "No s'han trobat coincidències. Prova un altre títol o ISBN, o completa la fitxa manualment.", unknownAuthor: "Autor desconegut",
    hint: "Es desen els textos disponibles en castellà, català i anglès. La fitxa segueix l'idioma del sistema; ISBN i editorial corresponen a l'edició seleccionada. Les pàgines es consulten a Open Library; si falten, es fa servir la paginació disponible a l'EPUB.",
    fallback: "No hi ha sinopsi en aquest idioma. Es mostra el text original disponible; pots afegir una versió manualment.",
    locale: "Idioma dels textos", savedProfile: "Fitxa que es desarà", title: "Títol", subtitle: "Subtítol", author: "Autors", year: "Any", isbn: "ISBN", publisher: "Editorial", publishDate: "Data de publicació", language: "Idioma de l'edició", pageCount: "Pàgines", subjects: "Temes / gèneres", description: "Sinopsi", coverUrl: "URL de la portada",
    fileCover: "Fer servir la portada del fitxer", localCover: "Portada des de l'equip", deleteBook: "Esborrar el llibre complet", cancel: "Cancel·lar", saving: "Desant…", confirmUpload: "Confirmar el llibre i pujar-lo", confirmSave: "Confirmar i desar la fitxa", refresh: "Actualitzar els tres idiomes",
    searchError: "No s'ha pogut consultar Open Library.", detailsError: "No s'ha pogut recuperar la fitxa.", saveError: "No s'ha pogut desar la fitxa.",
    collection: "Col·lecció", yourLibrary: "La teva biblioteca", read: "Llegir", edit: "Editar la fitxa", lookup: "Cercar informació del llibre", remove: "Eliminar", format: "Format", topics: "Temes", source: "Fitxa original a Open Library ↗",
    noDescription: "Encara no hi ha sinopsi. Cerca el llibre a Open Library o completa'n la fitxa.", empty: "No hi ha llibres", emptyHint: "Puja un fitxer o una carpeta amb una col·lecció.", enter: "Entrar", customize: "Personalitzar",
  },
  en: {
    searchLibrary: "Search by title, author or year", searchLibraryPlaceholder: "Title, author or year",
    novels: "Novels", graphicNovels: "Graphic novels", graphicNovel: "Graphic novel", bookType: "Book type",
    typeHint: "Unchecked: novel. Check this for a graphic novel or comic.", batchTypeHint: "Unchecked: novel. This selection applies to every file in the upload; you can change it later in each book's details.",
    collectionTypeHint: "Changing this checkbox applies the type to every book in the collection, including those hidden by the current filter. Unchecked: novel.",
    sort: "Sort by", sortName: "Name", sortAuthor: "Author", actions: "Actions", showActions: "Show book actions", hideActions: "Hide book actions", download: "Download", emptyNovels: "No novels", emptyGraphicNovels: "No graphic novels",
    catalogPages: "Pages in the edition listed on Open Library; these may differ from the reader's screens.", missingPages: "Open Library does not list a page count for this edition. You can enter it manually.",
    epubPageList: "Pages referenced in the EPUB. These may differ from the reader's screens.", epubFixedPages: "Pages counted from the EPUB's fixed layout.",
    library: "Library · Open Library", uploadTitle: "Identify the book before uploading", infoTitle: "Book information", close: "Close", file: "File",
    intro: "Search and select a match, review the details and confirm it is your book. You can also enter the information manually.",
    searchLabel: "Search by title, author or ISBN", searching: "Searching…", search: "Search", loading: "Loading the book details and available languages…",
    noResults: "No matches found. Try another title or ISBN, or fill in the details manually.", unknownAuthor: "Unknown author",
    hint: "Available texts in Spanish, Catalan and English are saved. The details follow the system language; ISBN and publisher refer to the selected edition. Page counts come from Open Library, with EPUB pagination used when unavailable.",
    fallback: "No synopsis is available in this language. The available original text is shown; you can add a version manually.",
    locale: "Text language", savedProfile: "Details to save", title: "Title", subtitle: "Subtitle", author: "Authors", year: "Year", isbn: "ISBN", publisher: "Publisher", publishDate: "Publication date", language: "Edition language", pageCount: "Pages", subjects: "Subjects / genres", description: "Synopsis", coverUrl: "Cover URL",
    fileCover: "Use the file's cover", localCover: "Cover from your computer", deleteBook: "Delete entire book", cancel: "Cancel", saving: "Saving…", confirmUpload: "Confirm book and upload", confirmSave: "Confirm and save details", refresh: "Refresh all three languages",
    searchError: "Could not search Open Library.", detailsError: "Could not load the book details.", saveError: "Could not save the book details.",
    collection: "Collection", yourLibrary: "Your library", read: "Read", edit: "Edit details", lookup: "Find book information", remove: "Delete", format: "Format", topics: "Subjects", source: "Original record on Open Library ↗",
    noDescription: "No synopsis yet. Find the book on Open Library or fill in its details.", empty: "No books", emptyHint: "Upload a file or a folder containing a collection.", enter: "Open", customize: "Customize",
  },
};

export const bookStrings = language => strings[bookLanguage(language)];
