const strings = {
  es: {
    setup: "Activa la IA y guarda una clave de OpenAI en el dashboard.", rateLimit: "Hay demasiadas consultas. Espera un momento y vuelve a intentarlo.", authError: "OpenAI ha rechazado la clave. Revisa las credenciales en el dashboard.", modelError: "El modelo no está disponible para esta cuenta. Revisa el modelo en el dashboard.", invalidQuery: "Revisa la consulta e inténtalo de nuevo.", refused: "No se pudo procesar esta petición. Prueba otra consulta sobre el catálogo.",
    ask: "Preguntar a la IA", title: "Pregunta a la IA: Consulta tu catálogo", prompt: "¿Qué quieres encontrar?", send: "Buscar", waiting: "Consultando el catálogo…", close: "Cerrar", cancel: "Cancelar", clear: "Quitar búsqueda IA",
    hint: "Busca por los datos de las fichas. Los resultados se combinan con tus filtros y la vista actual.", picturesHint: "Busca imágenes por nombre de archivo. No se analiza el contenido de las fotos.",
    demo: "Conecta con la Raspberry para usar la IA.", error: "No se pudo consultar la IA. Revisa la conexión y la configuración de OpenAI en el dashboard.", timeout: "La consulta ha tardado demasiado. Puedes reintentarlo.",
    matches: "coincidencias", visible: "visibles en esta vista", missing: "fichas con información incompleta", applied: "Búsqueda IA", examples: "Prueba con…", empty: "No hay resultados para esta búsqueda y los filtros actuales.",
    settingsTitle: "OpenAI · Búsqueda y recomendaciones", settingsHint: "La clave se guarda en la Raspberry. Las consultas usan la API de OpenAI y pueden tener coste.", enabled: "Activar IA del catálogo", key: "Clave API", keySaved: "Clave guardada · deja vacío para conservarla", keyEmpty: "Introduce tu clave API", model: "Modelo", rate: "Máximo de consultas por minuto", save: "Guardar", saving: "Guardando…", test: "Probar conexión guardada", testing: "Probando…", remove: "Eliminar clave", saved: "Configuración guardada.", removed: "Clave eliminada.", connected: "Conexión correcta.", loading: "Cargando configuración…", retry: "Reintentar", settingsError: "No se pudo cargar o guardar la configuración de OpenAI.", saveBeforeTest: "Guarda los cambios antes de probar la conexión.",
    samples: { movies: ["Películas de Tom Hanks", "Películas dirigidas por Spielberg", "Comedias de los años 90"], series: ["Series de ciencia ficción", "Series estrenadas antes de 2010", "¿Cuántas series tengo?"], books: ["Libros de Stephen King", "Libros publicados antes de 1980", "¿Cuántos libros tengo?"], games: ["Juegos de plataformas", "Juegos de Super Nintendo", "Juegos publicados en los años 90"], pictures: ["Fotos con vacaciones en el nombre", "Imágenes con 2024 en el nombre", "¿Cuántas imágenes tengo?"] },
  },
  ca: {
    setup: "Activa la IA i desa una clau d’OpenAI al dashboard.", rateLimit: "Hi ha massa consultes. Espera un moment i torna-ho a provar.", authError: "OpenAI ha rebutjat la clau. Revisa les credencials al dashboard.", modelError: "El model no està disponible per a aquest compte. Revisa el model al dashboard.", invalidQuery: "Revisa la consulta i torna-ho a provar.", refused: "No s’ha pogut processar aquesta petició. Prova una altra consulta sobre el catàleg.",
    ask: "Pregunta a la IA", title: "Pregunta a la IA: Consulta el teu catàleg", prompt: "Què vols trobar?", send: "Cerca", waiting: "Consultant el catàleg…", close: "Tanca", cancel: "Cancel·la", clear: "Treu la cerca IA",
    hint: "Cerca per les dades de les fitxes. Els resultats es combinen amb els filtres i la vista actual.", picturesHint: "Cerca imatges pel nom del fitxer. No s’analitza el contingut de les fotos.",
    demo: "Connecta amb la Raspberry per fer servir la IA.", error: "No s’ha pogut consultar la IA. Revisa la connexió i la configuració d’OpenAI al dashboard.", timeout: "La consulta ha trigat massa. Pots tornar-ho a provar.",
    matches: "coincidències", visible: "visibles en aquesta vista", missing: "fitxes amb informació incompleta", applied: "Cerca IA", examples: "Prova amb…", empty: "No hi ha resultats per a aquesta cerca i els filtres actuals.",
    settingsTitle: "OpenAI · Cerca i recomanacions", settingsHint: "La clau es desa a la Raspberry. Les consultes fan servir l’API d’OpenAI i poden tenir cost.", enabled: "Activa la IA del catàleg", key: "Clau API", keySaved: "Clau desada · deixa-ho buit per conservar-la", keyEmpty: "Introdueix la clau API", model: "Model", rate: "Màxim de consultes per minut", save: "Desa", saving: "Desant…", test: "Prova la connexió desada", testing: "Provant…", remove: "Elimina la clau", saved: "Configuració desada.", removed: "Clau eliminada.", connected: "Connexió correcta.", loading: "Carregant la configuració…", retry: "Torna-ho a provar", settingsError: "No s’ha pogut carregar o desar la configuració d’OpenAI.", saveBeforeTest: "Desa els canvis abans de provar la connexió.",
    samples: { movies: ["Pel·lícules de Tom Hanks", "Pel·lícules dirigides per Spielberg", "Comèdies dels anys 90"], series: ["Sèries de ciència-ficció", "Sèries estrenades abans del 2010", "Quantes sèries tinc?"], books: ["Llibres de Stephen King", "Llibres publicats abans del 1980", "Quants llibres tinc?"], games: ["Jocs de plataformes", "Jocs de Super Nintendo", "Jocs publicats als anys 90"], pictures: ["Fotos amb vacances al nom", "Imatges amb 2024 al nom", "Quantes imatges tinc?"] },
  },
  en: {
    setup: "Enable AI and save an OpenAI key in the dashboard.", rateLimit: "Too many requests. Wait a moment and try again.", authError: "OpenAI rejected the key. Check your credentials in the dashboard.", modelError: "The model is unavailable for this account. Check the model in the dashboard.", invalidQuery: "Review your query and try again.", refused: "This request could not be processed. Try another question about the catalog.",
    ask: "Ask AI", title: "Ask AI: Search your catalog", prompt: "What would you like to find?", send: "Search", waiting: "Searching the catalog…", close: "Close", cancel: "Cancel", clear: "Clear AI search",
    hint: "Search the information in your profiles. Results combine with your filters and current view.", picturesHint: "Find pictures by file name. Photo contents are not analyzed.",
    demo: "Connect to your Raspberry to use AI.", error: "The AI request failed. Check your connection and the OpenAI settings in the dashboard.", timeout: "The request took too long. Please try again.",
    matches: "matches", visible: "visible in this view", missing: "profiles with incomplete information", applied: "AI search", examples: "Try asking…", empty: "No results match this search and the current filters.",
    settingsTitle: "OpenAI · Search and recommendations", settingsHint: "The key is saved on your Raspberry. Queries use the OpenAI API and may incur charges.", enabled: "Enable catalog AI", key: "API key", keySaved: "Key saved · leave empty to keep it", keyEmpty: "Enter your API key", model: "Model", rate: "Maximum requests per minute", save: "Save", saving: "Saving…", test: "Test saved connection", testing: "Testing…", remove: "Delete key", saved: "Settings saved.", removed: "Key deleted.", connected: "Connection successful.", loading: "Loading settings…", retry: "Retry", settingsError: "Could not load or save OpenAI settings.", saveBeforeTest: "Save changes before testing the connection.",
    samples: { movies: ["Movies with Tom Hanks", "Movies directed by Spielberg", "Comedies from the 90s"], series: ["Science fiction series", "Series released before 2010", "How many series do I have?"], books: ["Books by Stephen King", "Books published before 1980", "How many books do I have?"], games: ["Platform games", "Super Nintendo games", "Games published in the 90s"], pictures: ["Pictures with holiday in the name", "Images with 2024 in the name", "How many pictures do I have?"] },
  },
};
export function catalogAIStrings(language) {
  const key = String(language || "es").toLowerCase().split(/[-_]/)[0];
  return strings[key === "cat" ? "ca" : key] || strings.es;
}

export function catalogAIError(error, language, fallback = "error") {
  const s = catalogAIStrings(language);
  const key = { AI_DISABLED: "setup", AI_NOT_CONFIGURED: "setup", AI_DEMO: "demo", AI_TIMEOUT: "timeout",
    AI_BUSY: "rateLimit", AI_RATE_LIMIT: "rateLimit", AI_UPSTREAM_RATE_LIMIT: "rateLimit", AI_AUTH_ERROR: "authError",
    AI_MODEL_ERROR: "modelError", AI_INVALID_QUERY: "invalidQuery", AI_INVALID_PROMPT: "invalidQuery", AI_REFUSED: "refused" }[error?.code];
  return s[key || fallback];
}
