const strings = {
  es: {
    title: "Obtener subtítulo", language: "Idioma del subtítulo", searching: "Buscando y guardando subtítulo…",
    hint: "Busca en OpenSubtitles y guarda el SRT junto al vídeo en la Raspberry. Sustituye el SRT existente.",
    saved: "Subtítulo guardado", exact: "Coincidencia con el fichero de vídeo.", fallback: "Elegido por la película y la versión disponible. Comprueba la sincronización.",
    restart: "Si el vídeo ya estaba reproduciéndose, vuelve a iniciarlo para cargar el subtítulo.",
    configure: "Configurar OpenSubtitles", setup: "Introduce tu clave de API y tu cuenta de OpenSubtitles.com una sola vez. Se guardan en la Raspberry.",
    help: "Cómo obtener la clave de API", apiKey: "Clave de API", username: "Usuario", password: "Contraseña",
    keep: "Guardada · deja vacío para conservarla", save: "Guardar cuenta", saving: "Guardando…", configured: "Cuenta guardada. Ya puedes obtener el subtítulo.",
    manual: "Hay un SRT seleccionado para subir. Quita la selección para buscar uno en internet.",
    failed: "No se pudo obtener el subtítulo. Inténtalo de nuevo.",
    SUBTITLE_NOT_CONFIGURED: "Configura tu cuenta de OpenSubtitles para obtener subtítulos.",
    SUBTITLE_AUTH_FAILED: "OpenSubtitles no acepta las credenciales. Revisa la clave, el usuario y la contraseña.",
    SUBTITLE_ACCESS_DENIED: "OpenSubtitles no permite la descarga. Revisa la cuenta, la clave de API y la cuota disponible.",
    SUBTITLE_LIMIT_REACHED: "Has alcanzado un límite de OpenSubtitles. Vuelve a intentarlo más tarde.",
    SUBTITLE_NOT_FOUND: "No se encontró un subtítulo completo y compatible en este idioma. Prueba otro idioma o sube un SRT.",
    SUBTITLE_PROVIDER_ERROR: "No se pudo conectar correctamente con OpenSubtitles. Inténtalo más tarde.",
    SUBTITLE_INVALID_DOWNLOAD: "La descarga no contiene un SRT válido. Se ha conservado el subtítulo anterior.",
    SUBTITLE_MOVIE_CHANGED: "El vídeo ya no está disponible o ha cambiado durante la búsqueda. Vuelve a abrir la ficha.",
    SUBTITLE_BUSY: "Ya se está obteniendo un subtítulo en la Raspberry. Espera a que termine.",
    SUBTITLE_SAVE_FAILED: "No se pudo guardar en la Raspberry. Comprueba el espacio libre y los permisos.",
    SUBTITLE_INVALID_SETTINGS: "Revisa los datos de la cuenta de OpenSubtitles.",
    SUBTITLE_DEMO: "Conecta con la Raspberry para configurar OpenSubtitles y descargar subtítulos.",
  },
  ca: {
    title: "Obtenir subtítol", language: "Idioma del subtítol", searching: "Cercant i desant el subtítol…",
    hint: "Cerca a OpenSubtitles i desa el SRT al costat del vídeo a la Raspberry. Substitueix el SRT existent.",
    saved: "Subtítol desat", exact: "Coincidència amb el fitxer de vídeo.", fallback: "Triat segons la pel·lícula i la versió disponible. Comprova la sincronització.",
    restart: "Si el vídeo ja s’estava reproduint, torna a iniciar-lo per carregar el subtítol.",
    configure: "Configurar OpenSubtitles", setup: "Introdueix la clau d’API i el compte d’OpenSubtitles.com una sola vegada. Es desen a la Raspberry.",
    help: "Com obtenir la clau d’API", apiKey: "Clau d’API", username: "Usuari", password: "Contrasenya",
    keep: "Desada · deixa-ho buit per conservar-la", save: "Desar el compte", saving: "Desant…", configured: "Compte desat. Ja pots obtenir el subtítol.",
    manual: "Hi ha un SRT seleccionat per pujar. Treu la selecció per cercar-ne un a internet.",
    failed: "No s’ha pogut obtenir el subtítol. Torna-ho a provar.",
    SUBTITLE_NOT_CONFIGURED: "Configura el compte d’OpenSubtitles per obtenir subtítols.",
    SUBTITLE_AUTH_FAILED: "OpenSubtitles no accepta les credencials. Revisa la clau, l’usuari i la contrasenya.",
    SUBTITLE_ACCESS_DENIED: "OpenSubtitles no permet la descàrrega. Revisa el compte, la clau d’API i la quota disponible.",
    SUBTITLE_LIMIT_REACHED: "Has arribat a un límit d’OpenSubtitles. Torna-ho a provar més tard.",
    SUBTITLE_NOT_FOUND: "No s’ha trobat cap subtítol complet i compatible en aquest idioma. Prova un altre idioma o puja un SRT.",
    SUBTITLE_PROVIDER_ERROR: "No s’ha pogut connectar correctament amb OpenSubtitles. Torna-ho a provar més tard.",
    SUBTITLE_INVALID_DOWNLOAD: "La descàrrega no conté un SRT vàlid. S’ha conservat el subtítol anterior.",
    SUBTITLE_MOVIE_CHANGED: "El vídeo ja no està disponible o ha canviat durant la cerca. Torna a obrir la fitxa.",
    SUBTITLE_BUSY: "Ja s’està obtenint un subtítol a la Raspberry. Espera que acabi.",
    SUBTITLE_SAVE_FAILED: "No s’ha pogut desar a la Raspberry. Comprova l’espai lliure i els permisos.",
    SUBTITLE_INVALID_SETTINGS: "Revisa les dades del compte d’OpenSubtitles.",
    SUBTITLE_DEMO: "Connecta amb la Raspberry per configurar OpenSubtitles i descarregar subtítols.",
  },
  en: {
    title: "Get subtitle", language: "Subtitle language", searching: "Finding and saving subtitle…",
    hint: "Searches OpenSubtitles and saves the SRT beside the video on the Raspberry. Replaces the existing SRT.",
    saved: "Subtitle saved", exact: "Matched to the video file.", fallback: "Selected by movie and available release. Check the timing.",
    restart: "If the video was already playing, start it again to load the subtitle.",
    configure: "Configure OpenSubtitles", setup: "Enter your API key and OpenSubtitles.com account once. They are saved on the Raspberry.",
    help: "How to get an API key", apiKey: "API key", username: "Username", password: "Password",
    keep: "Saved · leave blank to keep", save: "Save account", saving: "Saving…", configured: "Account saved. You can now get the subtitle.",
    manual: "An SRT is selected for upload. Clear the selection to search online.",
    failed: "Could not obtain the subtitle. Please try again.",
    SUBTITLE_NOT_CONFIGURED: "Configure your OpenSubtitles account to get subtitles.",
    SUBTITLE_AUTH_FAILED: "OpenSubtitles rejected the credentials. Check your API key, username and password.",
    SUBTITLE_ACCESS_DENIED: "OpenSubtitles denied the download. Check your account, API key and remaining quota.",
    SUBTITLE_LIMIT_REACHED: "You have reached an OpenSubtitles limit. Try again later.",
    SUBTITLE_NOT_FOUND: "No compatible full subtitle was found in this language. Try another language or upload an SRT.",
    SUBTITLE_PROVIDER_ERROR: "Could not communicate with OpenSubtitles. Try again later.",
    SUBTITLE_INVALID_DOWNLOAD: "The download is not a valid SRT. The previous subtitle has been kept.",
    SUBTITLE_MOVIE_CHANGED: "The video is no longer available or changed during the search. Open the movie details again.",
    SUBTITLE_BUSY: "A subtitle is already being obtained on the Raspberry. Wait for it to finish.",
    SUBTITLE_SAVE_FAILED: "Could not save on the Raspberry. Check free space and permissions.",
    SUBTITLE_INVALID_SETTINGS: "Check your OpenSubtitles account details.",
    SUBTITLE_DEMO: "Connect to the Raspberry to configure OpenSubtitles and download subtitles.",
  },
};

export function movieSubtitleStrings(language) {
  return strings[String(language || "es").slice(0, 2)] || strings.es;
}
